name: Keith Webber
description: Random Variable 

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: kramdown
# redcarpet:
#   extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: 
permalink: /:year/:month/:title/
owner:
    name: Keith Webber
    twitter: kthwbbr
    github: townie
    linkedin: webberkeith
    # disqus_shortname: #

ga_id: UA-43266357-8
ga_username: #

timezone: Africa/Accra
